trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build and Test'
  steps:
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '11'
      addToPath: true
  - script: ./gradlew build
    displayName: 'Build Project'
  - script: ./gradlew test
    displayName: 'Run Tests'
